name: Maroine Action
on: ['workflow_dispatch','push']

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: sqdqsdqsd
        uses: maroine-soprano/my-action@v1.2
        with:
          fullname: "maroine khallouqsdqs"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.sqdqsdqsd.outputs.hello-description }}"
