name: run-script
on: ['push']

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./scripts
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Set up permission
              run: chmod +x ./script.sh
            - name: run script
              run: ./script.sh
