name: workflow-contaxt
on: ["push"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: action context
        env:
          GITHUB_SEC: ${{ secrets.SEC }}
        run: echo $GITHUB_SEC
