name: workflow-contaxt
on: ["push"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: action context
        env:
          GITHUB_CONTEXT: ${{ github.action }}
        run: echo $GITHUB_CONTEXT
