name: worflow-command
on: ['push']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: add val
        run: echo "KEY= value" >> $GITHUB_ENV
      - name: red val
        run: |
          echo $KEY
